### PR TITLE
Temporary fix to set a valid MAC address on the BBGW

### PR DESCRIPTION
**Pull request by serpent213**
This nvs file has the MAC address set to `00:00:00:00:00:00` instead of
`00:00:de:ad:be:ef`. In this case the interface uses its internal MAC
addresses with a TI vendor id. See
http://processors.wiki.ti.com/index.php/WL18xx_Writing_MAC_address

### CODE REVIEW

**Comment by improper** [comment]
Maybe this should be propagated upstream? Or is there a good reason for the `0xdeadbeef`?

**Comment by fhunleth** [comment]
My understanding is that the reason it's hardcoded to `0xdeadbeef` is to remind people that they haven't run the TI calibration program on the WiFi module. I think that's needed to pass FCC, but I really don't know. Given that the official Beagebone Debian repository sets the MAC address with a bash script, I don't see any reason that we set the MAC too, and the zero-out way seems way easier than the way Debian does it. 

I'd like to do it a different way, though. I'd like to use the official nvs file and have a script that zeros out the MAC. That way if TI produces a new nvs file, it can be automatically fixed. Also, people can verify that we're including the official nvs file if they wish.

What needs to happen is that we need to make a Buildroot package that contains or downloads the nvs file (downloads would be preferred). Then it would zero out the MAC and copy the result to the right place. If you're not familiar with Buildroot, I can help out on this. What I need, though, is a `dd` command that zeros out the MAC. It's probably something like `dd if=/dev/zero of=wl127x-nvs.bin bs=1  seek=??? count=6`. 

Could you do at least that or start a Buildroot package?

**Comment by serpent213** [comment]
Yes, I will gladly make a Buildroot package, I might need some help here and there, though.  :)

My idea for the final fix was to port the Debian shell script to Elixir, maybe just parts of it, and include it in nerves_system_bbb. Reading the MAC from the EEPROM and patching the nvs wouldn't be too hard. Then we would have the MAC that is printed on the sticker on the board, which is what the user would expect, I think.

**Comment by serpent213** [comment]
The official source for the nvs file seems to be a TI git repo: https://git.ti.com/wl12xx/ti-utils

The nvs file in there is preset with the MAC `00:da:36:16:de:eb`, if I got it right.

I'm wondering what the calibration does exactly, what its benefits are. Will try to find out...

ti-utils is available as a Buildroot package, but it uses a GitHub fork of the repo that has not been updated since 2011: https://github.com/gxk/ti-utils.

**Comment by fhunleth** [comment]
It's been a while, but I'm finally getting back to the wl1835 since I'm using it on a work project. See #31 for clearing out the MAC address so that the one assigned by TI in manufacturing gets used. I wanted to use the `calibrator` app to clear it since that seemed more maintainable than hardcoding the MAC address offset in the file, but that program is intended to be built on the BBB and doesn't compile nicely on the host. 

To dump some more information here if anyone needs to refer to it in the future, the ti-utils package is now at http://git.ti.com/wilink8-wlan/18xx-ti-utils. In addition to the calibrator tool, there's a really useful tool called `wlconf` for configuring the module the way the TI got it certified. The configuration that we currently have included (the one for the BBGW), is for a wl1835 w/ two 2.4 GHz antennas and the Class 2 Permissive Change (C2PC) applied. If you're working with a different wl18xx module, you may need to use a different configuration file to match what TI got certified.

**Pull request closed without merging**
