### PR TITLE
[WIP] Update README to reflect recent kernel changes.

### PR DESCRIPTION
**Pull request by ConnorRigby**
As described in #50, Linux is dropping support for loading device tree overlays at runtime. This cause a lot of docs to be out of date. The docs for ADC and SPI seem kind of pointless to me now, since you can't just read the section here and be ready to roll. You have to read another guide, and still possibly be missing things. Maybe we should pull in a simplified version of the official beagle board guide, that describes how to use the Mix build environment to load in device tree overlays?

### CODE REVIEW

**Comment by fhunleth** [comment]
Are you planning on amending this PR with updated information on ADC and SPI?

I feel that we need to have something here to get people started since there's a decent amount of translation between the Beaglebone Debian-based docs and Nerves.

**Comment by ConnorRigby** [comment]
Yeah i'm reading thru that document i linked first. It looks like ADC is enabled by default now. Unfortunately, i think loading device trees isn't exactly going to be simple anymore as @elcritch pointed out in #50

**Comment by ConnorRigby** [comment]
I tried following the bb.org guide on enabling uboot overlays, and it didn't work even after updating uboot. Timed out for now, but i'll take another pass at this tomorrow morning. I'm sure i'm missing something.

FWIW the general idea is to set a environment config in either `uEnv.txt` or in `fwup.conf` should cause the dtb to be loaded.

**Comment by elcritch** [comment]
@ConnorRigby -- it'd be great if you figure out the u-boot overlays. I tried a few iterations and never quite got them working. :/ I suspect there may be something in the u-boot.cmd setup. 

I also posted some questions on the BB forums, and got the PRU's working on the PB, but not via the u-boots. Here's the link in case it helps: [PocketBeagle PRU's not loading in Buildroot Image](https://beagleboard.org/discuss?place=topic%2Fbeagleboard%2Fci_v6wD_exU%2Fdiscussion)

Robert Nelson said there's a path for a u-boot cape manager, but I think that's already included in the u-boot patches. Though I'm not sure if it's up to date with the latest.

**Comment by ConnorRigby** [comment]
I _really_ like that idea. 
`uboot_setenv(uboot-env, "uboot_overlay_addr0", "/path/to/dtb"` doesn't seem to work at the moment, but when i get it working, i think we should put that in the default configuration.

**Comment by fhunleth** [comment]
This branch is getting closer. I've added a lot of changes to support the new overlays. Unfortunately, it required me to finally fix the U-boot environment size to be 128 KB instead of 8 KB since the new scripts didn't fit. Setting it to 8 KB a long time ago was a mistake, but it stuck since if you change it, you have to figure out a way to migrate the U-boot environment and that's not easy. Here's where I'm at:

1. New U-boot is booting - Connor did most of this work. I applied a few more patches.
2. U-boot reads the environment - It didn't use to do this, but this is needed to force overlays to load.
3. Added SquashFS support - It's currently very slow, but working. The Linux kernel, device tree and all of the overlays are pulled from the `/boot` and `/lib/firmare` directories in the rootfs. The reason I did this was that the number of files involved just got to be way to many to sanely deal with in `fwup`.
4. Updated to Linux 4.14 - The kernel hasn't been trimmed. Expect big builds.
5. Updated bborg-overlays - This is in `nerves_system_br`.

I've been testing everything with Buildroot 2018.05. This has minor version bumps all over, but I don't believe that it affects this work if you want to test out where I'm at.

**Comment by fhunleth** [comment]
Here are some dt overlays loading on an original BBB:
```
U-Boot 2018.03 (Jun 05 2018 - 16:41:37 -0400)

CPU  : AM335X-GP rev 2.0
I2C:   ready
DRAM:  512 MiB
No match for driver 'omap_hsmmc'
No match for driver 'omap_hsmmc'
Some drivers were not found
Reset Source: Power-on reset has occurred.
RTC 32KCLK Source: External.
MMC:   OMAP SD/MMC: 0, OMAP SD/MMC: 1
Loading Environment from MMC... OK
Board: BeagleBone Black
BeagleBone Black:
BeagleBone: cape eeprom: i2c_probe: 0x54:
BeagleBone: cape eeprom: i2c_probe: 0x55:
BeagleBone: cape eeprom: i2c_probe: 0x56:
BeagleBone: cape eeprom: i2c_probe: 0x57:
board_rev=[0A5B] ...
loading /boot/zImage ...
4166008 bytes read in 8379 ms (485.4 KiB/s)
uboot_overlays: [uboot_base_dtb=am335x-boneblack-uboot-univ.dtb] ...
uboot_overlays: [uboot_base_dtb=am335x-boneblack-uboot.dtb] ...
loading /boot/am335x-boneblack.dtb ...
60851 bytes read in 281 ms (210.9 KiB/s)
uboot_overlays: [fdt_buffer=0x60000] ...
uboot_overlays: loading /lib/firmware/BB-BONE-eMMC1-01-00A0.dtbo ...
1440 bytes read in 191 ms (6.8 KiB/s)
uboot_overlays: uboot loading of [/lib/firmware/BB-HDMI-TDA998x-00A0.dtbo] disabled by /boot/uEnv.txt [disable_uboot_overlay_video=1]...
uboot_overlays: loading /lib/firmware/BB-ADC-00A0.dtbo ...
711 bytes read in 228 ms (2.9 KiB/s)
uboot_overlays: loading /lib/firmware/univ-bbb-Exx-00A0.dtbo ...
105020 bytes read in 193 ms (531.3 KiB/s)
debug: [console=ttyS0,115200n8 coherent_pool=1M bone_capemgr.uboot_capemgr_enabled=1 root=/dev/mmcblk0p2 rootfstype=squashfs rootwait] ...
debug: [bootz 0x82000000 - 88000000] ...
## Flattened Device Tree blob at 88000000
   Booting using the fdt blob at 0x88000000
   reserving fdt memory region: addr=88000000 size=88000
   Loading Device Tree to 8ff75000, end 8fffffff ... OK

Starting kernel ...

Booting Linux on physical CPU 0x0
Linux version 4.14.47 (fhunleth@halfmarathon) (gcc version 6.3.0 (crosstool-NG crosstool-ng-1.23.0)) #1 PREEMPT Wed Jun 6 11:23:50 EDT 2018
CPU: ARMv7 Processor [413fc082] revision 2 (ARMv7), cr=10c5387d
CPU: PIPT / VIPT nonaliasing data cache, VIPT aliasing instruction cache
OF: fdt: Machine model: TI AM335x BeagleBone Black
Memory policy: Data cache writeback
cma: Reserved 48 MiB at 0x9d000000
CPU: All CPU(s) started in SVC mode.
AM335X ES2.0 (sgx neon)
random: get_random_bytes called from start_kernel+0x8c/0x378 with crng_init=0
Built 1 zonelists, mobility grouping on.  Total pages: 129920
Kernel command line: console=ttyS0,115200n8 coherent_pool=1M bone_capemgr.uboot_capemgr_enabled=1 root=/dev/mmcblk0p2 rootfstype=squashfs rootwait
PID hash table entries: 2048 (order: 1, 8192 bytes)
```

If you're testing on a PocketBeagle, the universal overlay doesn't work since there's an if statement in U-Boot to skip cape probing. I think that the default PocketBeagle DT might be good enough.

I also made a pass on the kernel config. It's not perfect, but I think that it's ready for someone to look into the PRU.

**Comment by ConnorRigby** [comment]
Just booted up on pocket beagle:
```
00:00:11.634 [warn]  erlinit: error setting controlling terminal: /dev/ttyGS0

00:00:11.648 [error] EXT4-fs (mmcblk0p4): VFS: Can't find ext4 filesystem

00:00:11.648 [warn]  erlinit: Cannot mount /dev/mmcblk0p4 at /root: Invalid argument
Environment does not fit into available sectors
                                               Nerves.Runtime.Helpers imported. Run h(Nerves.Runtime.Helpers) for more info
iex(1)> 
00:00:12.773 [warn]  Nerves.Runtime.KV could not find executable fw_printenv

```

**Comment by ConnorRigby** [comment]
I didn't get a usb serial device upon boot either it doesn't seem.

**Comment by fhunleth** [comment]
I didn't verify the USB gadget serial device in the kernel arguments yet. My trivial mapping of old kernel params to new ones must have missed it.

Also, I see that `fw_printenv` is missing for you. I suppose that `uboot-tools` somehow got disabled?

**Comment by ConnorRigby** [comment]
Same results on beagle bone green. Not really sure why `fw_printenv` is missing. I just cloned `nerves_system_br` `br-2018.05` branch, and did a normal build of this branch

**Comment by ConnorRigby** [comment]
`uboot-tools` is enabled

**Comment by ConnorRigby** [comment]
also shouldn't `bone_capemgr.uboot_capemgr_enabled=1` be removed?

**Comment by ConnorRigby** [comment]
Sorry for the spam but one more development:
```
iex(3)> Nerves.Runtime.cmd("fw_printenv", [], :return)
{"Environment does not fit into available sectors\n", 1}
iex(4)> 
```

It looks like that log is a bug in Nerves.Runtime: https://github.com/nerves-project/nerves_runtime/blob/db48a4b81a087058d9f6ebfc486586307eeb026e/lib/nerves_runtime/kv.ex#L90-L99

**Comment by elcritch** [comment]
@fhunleth -- moving to 4.9 kernel I'd found similar issues as you're having above. Took me forever, but it appeared to be related to some modules which needed to be included. There's a few changes in naming/setup of the USB otg networking modules among others. 

Check out: https://github.com/elcritch/nerves_system_bbb_ti/blob/8213ccb42d7a74da88bd30f77a6a2b9fda104bee/linux/rcn-linux-4.9.82-ti-rt.defconfig#L392 

I may actually have some free time to test the PRU's on this this week! 

@ConnorRigby did you ever get the uboot overlays working?

**Comment by fhunleth** [comment]
I haven't looked into anything USB yet, so thanks for sending that reference over.

**Comment by fhunleth** [comment]
I haven't looked into anything USB yet, so thanks for sending that reference over.

**Comment by ConnorRigby** [comment]
I poked around this morning but timed out and had to work on some other stuff. If i read the above correctly it looks like @fhunleth has overlays working

**Comment by fhunleth** [comment]
FYI - I fixed the Nerves.Runtime.KV error with calling fw_printenv and gadget mode works.

I think the following is left:
1. Someone else besides me test out and have success with device tree overlays
2. Decide whether to enable the universal overlay by default
3. Document how to use device tree overlays
4. Make sure the PRU works with Linux 4.14
5. Review and update `docs/kernel.md`
6. Review the kernel's IP network settings. I've looked at most other places.
7. Verify WiFi works
8. Speed up squashfs - it currently takes 8 seconds to load the kernel from U-boot which is pretty ridiculous.

**Comment by ConnorRigby** [comment]
I'll test out PRUs and WiFi in a few. I can probably take a pass over the `docs/kernel.md` while im waiting for the build also.

**Comment by ConnorRigby** [comment]
so on bbgw i've tried
doing `modprobe wl18xx` and `ip addr`.
the wl18xx module loads, but i never get a new device in `ip addr`.


as for PRU's i tried [this](https://elinux.org/Beagleboard:BeagleBoneBlack_Debian#U-Boot_PRU_Options)
```
uboot_setenv(uboot-env, "uboot_overlay_pru", "/lib/firmware/AM335X-PRU-RPROC-4-14-TI-00A0.dtbo")
```
and
```
uboot_setenv(uboot-env, "uboot_overlay_pru", "/lib/firmware/AM335X-PRU-UIO-00A0.dtbo")
```

Both happily loaded their respective dtbs, but i never get a device in `/sys/class/remoteproc/`

This _could_ be related to bbgw tho maybe?

**Comment by elcritch** [comment]
It shouldn't be anything specific to the BBGWs...

Are you getting the TI OMAP timer remoteproc either? If not, it's most
likely more kernel module related issues. You need all the OMAP /
RemoteProc / PRU modules loaded or statically compiled. I prefer the static
drivers since the PRU's load much quicker.

**Comment by ConnorRigby** [comment]
I get remoteproc0 which I believe is the power management chip or something like that, so remoteproc is enabled. I also get a uevent message like 5 minutes after boot with some information about the prus but now sure what to make of it. Is there a Kernel module for prus also?

**Comment by elcritch** [comment]
Oh, yes it can take a while for PRU's to load (on 4.4 it was around 80 seconds). Though at that point you should get something in `remoteproc`. 

There's not a driver per se, but the rpmsg module is the easiest way to load them. Once that's loaded you can start a pru firmware driver with it. The PRU code can then tell the kernel it's ready which creates a /dev/rpmsg* device.

**Comment by elcritch** [comment]
Could you post the last messages you get about the PRU's you're getting?

**Comment by ConnorRigby** [comment]
```
iex(5)> cmd("modprobe uio")      
0
iex(6)> cmd("modprobe uio_pruss")
0
iex(7)> cmd("ls /sys/class/remoteproc")
remoteproc0
0
iex(8)> 
00:03:25.896 [debug] UEvent Unhandled: %{"action" => "bind", "devpath" => "/devices/platform/ocp/4a300000.pruss", "driver" => "pruss_uio", "modalias" => "of:NprussT<NULL>Cti,pruss-v2", "of_compatible_0" => "ti,pruss-v2", "of_compatible_n" => "1", "of_fullname" => "/ocp/pruss@4a300000", "of_name" => "pruss", "seqnum" => "1469", "subsystem" => "platform"}
iex(8)> cmd("ls /sys/class/remoteproc")
remoteproc0
```

**Comment by ConnorRigby** [comment]
That is with `uboot_overlay_pru=/lib/firmware/AM335X-PRU-RPROC-4-14-TI-00A0.dtbo`

**Comment by fhunleth** [comment]
FYI - The new version of Buildroot will not build the current `nerves_system_bbb` due to a build issue with the dtc library. Once fix to this is to get this branch merged. Could anyone using the BBB who has time to help me push this across the finish line let me know?

**Comment by ConnorRigby** [comment]
@fhunleth i have BBGW and BBP available. Ping me when youre ready and i can help out with this.

**Comment by fhunleth** [comment]
This patch set is superseded by #76. I haven't run code on the PRUs, but we now match Beagleboard's Debian configuration for device tree overlays for the PRUs, so I'd expected it to either work or be really close.

**Pull request closed without merging**
