### PR TITLE
Add getopts needed by config-pin

### PR DESCRIPTION
**Pull request by rob-brown**

### CODE REVIEW

**Comment by ConnorRigby** [comment]
Does config-pin even work right now? i thought it has been depreciated.

**Comment by rob-brown** [comment]
Now that I have `getopts` included I'm playing around with `config-pin` and it doesn't appear to work. For example, running `cmd "config-pin 911 uart"` prints

```
P9_11 pinmux file not found!
Please verify your device tree file
```

Though I can see `/sys/devices/platform/ocp/ocp:P9_11_pinmux` exists.

**Comment by ConnorRigby** [comment]
i've been a bit confused by how device trees work now, but i think you will have to load the `universal_io` overlay before config-pin might even work. @fhunleth might be able to help more, but i believe he just uses device trees, rather than overlays or config-pin

**Comment by rob-brown** [comment]
I got it figured out. I tried running this:

```elixir
cmd("fw_setenv uboot_overlay_addr4 /lib/firmware/BB-UART4-00A0.dtbo")
```

That gave me this error:

```
Error opening lock file /var/lock/fw_printenv.lock
```

I'm not sure why `fw_setenv` doesn't work out of the box. It's specifically mentioned in the [README](https://github.com/nerves-project/nerves_system_bbb/blob/master/README.md#device-tree-overlays). 

So then I tried modifying `provisioning.conf`. I added these lines:

```
uboot_setenv(uboot-env, "uboot_overlay_addr4", "/lib/firmware/BB-UART1-00A0.dtbo")
uboot_setenv(uboot-env, "uboot_overlay_addr5", "/lib/firmware/BB-UART2-00A0.dtbo")
uboot_setenv(uboot-env, "uboot_overlay_addr6", "/lib/firmware/BB-UART4-00A0.dtbo")
```

That made it work. 

By the way it looks like `universal-io` is already enabled from `provisioning.conf`.

```
uboot_setenv(uboot-env, "enable_uboot_cape_universal", "1")
```

Though that doesn't explain why `config-pin` doesn't work.

**Pull request closed without merging**
