### PR TITLE
Add ti-cgt-pru support

### PR DESCRIPTION
**Pull request by elcritch**

### CODE REVIEW

**Comment by ConnorRigby** [comment]
I haven't tried but if it works, thanks!

**Comment by elcritch** [comment]
Certainly! And you'll want to take a look at https://github.com/elcritch/pru_blink -- the main required change is adding `make_env: %{ "PRU_CGT" => "\${NERVES_TOOLCHAIN}/share/ti-cgt-pru/"}, ` to the project config. Then it should all work.

**Comment by fhunleth** [comment]
This is really awesome!! 

The bad news is that we don't package tools that run on the host in our systems. This only works on Linux and if you build the system locally. If you were to create the system artifact, it would not be in it since the `host/*` directories aren't included. We put the host-specific tools in toolchain artifacts (see the toolchain repo). For Buildroot, we untar the toolchains to Buildroot's host directory and then Buildroot intermingles host tools that it builds with it. 

I did some checking around, and the PRU C compiler is really annoying to get. It seems like you have to go through TI's CCS IDE? The Buildroot packaging seems to download pre-compiled binaries? Buildroot's licensing information for the compiler suggest that it's open source, so one would think that a source code repo is around somewhere. Until `mix` supports some way of installing host-side packages (or we invent a way for Nerves), I think that only way forward for now is to give people instructions on how to install the compiler on their systems.

**Comment by elcritch** [comment]
Shoot! It seemed like it was going to be _too_ easy. 

That makes sense, I haven't tried uploading a build artifact yet and just running it locally on my Linux machine. Yes, the PRU C compiler is particularly frustrating to get download unless you have the direct link. TI's site has multiple "PRU Tools" sites of which half don't seem to work anymore. You can download it as part of the CCS IDE but there is also a page with direct download links which the buildroot packages reference. 

As to whether it's possible to build the PRU C compiler, that I'm not aware of. I've never seen the actual source for it anywhere and the TI license appears to be a form of BSD/MIT style license. While fantastic that TI is really liberal in licensing the support libraries the source for the PRU C compiler doesn't appear to be out there anywhere. I've toyed around with the idea of trying to create an LLVM backend for the PRU's, but that'd be a bit of work! At that point it'd probably easier to write an (elaborate) Elixir macro that compiles a subset of Elixir AST down to PRU assembly. Ah dreams. :-)

**Comment by elcritch** [comment]
For the meantime it'd likely be simplest to provide a script that downloads the PRU C compiler binaries similar to what the buildroot ti-cgt-pru package does. I'll give some thought to it this week and see if I can think up any ideas. 

The idea of a mix install for host tools might be handy. that sounds feasible. It's not essentially much different than what say the elixir_make mix compiler does. Theoretically it'd be possible to setup the makefile $PRU_CGT path to point towards a deps/ or _build/ directory instead of $NERVES_TOOLCHAIN.

**Comment by mobileoverlord** [comment]
A solution for supporting PRU's is being managed further up in the tooling. @elcritch as more info

**Pull request closed without merging**
