### PR TITLE
Add the device tree for the BBG gateway

### PR DESCRIPTION
**Pull request by fhunleth**

### CODE REVIEW

**Review by ConnorRigby — APPROVED** [review]

**Comment by jasonmj** [comment]
First off, thanks for this quick action on supporting this device. Hopefully, it's not too much trouble to add the support needed for usb, ethernet, and wifi. 

After adding this patch, I didn't notice a difference in the functionality of the WL1835MODGBMOC wireless/bluetooth combo module or the LAN9512/4(i) U6 usb/ethernet combo module. I did however see that the blue leds near the usb/ethernet module started blinking for the first time. However, neither usb nor ethernet respond when plugged in (no lights, no power). Despite this, when I run `VintageNet.info` I do see that both `usb0` and `eth0` interfaces are present and configured, yet they are :disconnected. I also see them returned by `ifconfig`. I'm using the same VintageNet configuration that works flawlessly for me on an RPI3, so I think something else is missing.

I've read into a bit and found that there are a few challenging factors with these modules: 
1. The usb/ethernet module includes an onboard eeprom that needs configuration according to [this comment](https://forum.seeedstudio.com/t/beaglebone-green-gateway-connman-assigns-new-mac-on-reboot/260113/3). 
2. The wifi/bt module _should_ work like the other Wilink8's, but I'm not seeing it in `VintageNet.info` (it's not present) or in `ifconfig`. I've tried adding the `CONFIG_WLCORE` from "Texas Instrument devices" alongside the existing `CONFIG_WL18XX` and `CONFIG_WLCORE_SDIO` entries in the defconfig. I found `/lib/firmware/BB-BBGG-WL1835-00A0.dtbo` in the custom system's target files, which might be what I need, but I'm not sure how to add it as a device tree overlay because the `nerves_system_bbb` repo doesn't seem to include a `config.txt` like the RPI systems do. Perhaps I just need to add one? 

Hopefully, this gives you some decent context into the scenario. I'll keep working on it here to see if I can make some progress.

**Comment by jasonmj** [comment]
Oh, and one more thing... this might be important: 

When the device boots up, I see `loading /boot/am335x-boneblack-uboot-univ.dtb` rather than `am335x-bonegreen-gateway.dtb`. Is that normal or should I be seeing the gateway device tree being used?

**Comment by fhunleth** [comment]
That last comment was super helpful. It doesn't look like the BBBG gateway is known by the U-Boot script. This is at https://github.com/nerves-project/nerves_system_bbb/blob/main/uboot/0001-am335x_evm-uEnv.txt-bootz-n-fixes.patch#L652-L692. That code looks at the board code in the EEPROM and sets the device tree file. 

There's probably an upstream patch to fix this. I'll look next break that I get.

**Comment by jasonmj** [comment]
Aha! I was _just_ reviewing the `uboot.env` script, felt like I was getting closer. I'm learning more about how the bbb's handle device trees while compiling some more tests on the bbgg I have here.

**Comment by jasonmj** [comment]
Here's the output shown on boot from a clean nerves install running the `support-bbg-gateway` branch on my BBGG: 

```
U-Boot SPL 2018.07 (Feb 24 2022 - 14:49:53 +0000)
Trying to boot from MMC1
Loading Environment from MMC... OK


U-Boot 2018.07 (Feb 24 2022 - 14:49:53 +0000)

CPU  : AM335X-GP rev 2.1
I2C:   ready
DRAM:  512 MiB
No match for driver 'omap_hsmmc'
No match for driver 'omap_hsmmc'
Some drivers were not found
Reset Source: Power-on reset has occurred.
RTC 32KCLK Source: External.
MMC:   OMAP SD/MMC: 0, OMAP SD/MMC: 1
Loading Environment from MMC... OK
Board: BeagleBone Black
<ethaddr> not set. Validating first E-fuse MAC
BeagleBone Black:
BeagleBone: cape eeprom: i2c_probe: 0x54:
BeagleBone: cape eeprom: i2c_probe: 0x55:
BeagleBone: cape eeprom: i2c_probe: 0x56:
BeagleBone: cape eeprom: i2c_probe: 0x57:
Net:   eth0: MII MODE
cpsw
Saving Environment to MMC... Writing to MMC(0)... OK
board_name=[A335BNLT] ...
board_rev=[GG1A] ...
loading /zImage.a ...
2828440 bytes read in 180 ms (15 MiB/s)
uboot_overlays: [uboot_base_dtb=am335x-boneblack-uboot-univ.dtb] ...
uboot_overlays: Switching too: dtb=am335x-boneblack-uboot-univ.dtb ...
loading /boot/am335x-boneblack-uboot-univ.dtb ...
215402 bytes read in 10 ms (20.5 MiB/s)
uboot_overlays: [fdt_buffer=0x60000] ...
uboot_overlays: loading /lib/firmware/BB-BONE-eMMC1-01-00A0.dtbo ...
1614 bytes read in 8 ms (196.3 KiB/s)
uboot_overlays: loading /lib/firmware/BB-HDMI-TDA998x-00A0.dtbo ...
5330 bytes read in 8 ms (650.4 KiB/s)
uboot_overlays: loading /lib/firmware/BB-ADC-00A0.dtbo ...
654 bytes read in 7 ms (90.8 KiB/s)
debug: [console=ttyS0,115200n8 coherent_pool=1M bone_capemgr.uboot_capemgr_enabled=1 root=/dev/mmcblk0p2 rootfstype=squashfs rootwait coherent_pool=1M net.ifnames=0 omap_wdt.early_enable=1 omap_wdt.timer_margin=120 quiet] ...
debug: [bootz 0x82000000 - 88000000] ...
## Flattened Device Tree blob at 88000000
   Booting using the fdt blob at 0x88000000
   reserving fdt memory region: addr=88000000 size=96000
   Loading Device Tree to 8ff67000, end 8fffffff ... OK

Starting kernel ...
```

Interestingly, `board_rev=[GG1A]` seems to use the same rev as the BBGW in the U-Boot script. I think I'll try dropping in the BBGG .dtb instead of the BBGW and see if that works.

**Comment by jasonmj** [comment]
After attempting my own patches for a while here, I just found these, which appear to include the Gateway: 
https://github.com/RobertCNelson/Bootloader-Builder/blob/master/patches/v2019.04/0001-am335x_evm-uEnv.txt-bootz-n-fixes.patch#L352-L394

I'll try to merge with Nerves.

**Comment by fhunleth** [comment]
@jasonmj If there's a patch for using U-Boot v2018.07, that's the least risky option. If not, it's ok to update the U-Boot version, but that's a little more involved. I'd be in favor of updating to the latest U-Boot release so that the SquashFS patches can be dropped.

**Comment by jasonmj** [comment]
I'm testing a manual merge of changes relevant to the BBGG I added to `uboot/0001-am335x_evm-uEnv.txt-bootz-n-fixes.patch` and `uboot/0002-U-Boot-BeagleBone-Cape-Manager.patch`. 

Looks like the oldest version where the Green Gateway patches were included is v2019.04. 

Maybe I can update `BR2_TARGET_UBOOT_CUSTOM_VERSION_VALUE="2019.04"` in `nerves_defconfig` and add the patches found [here](https://github.com/RobertCNelson/Bootloader-Builder/tree/master/patches/v2019.04) to the `uboot` directory of the system?

This is beginning to feel a bit "involved" :smiley:, but I think I'm still making forward progress.

**Comment by fhunleth** [comment]
@jasonmj You've figured out the critical part. I think this is a ~10 minute update for me once I get set up. I don't mind doing that since you've done the majority of the work for me to be super efficient with the patch management piece. Then I'll need your help to verify that it all works on the BBGW.

**Comment by jasonmj** [comment]
Awesome! I'm glad it seems like my research was helpful. I'll sit tight and let you get a crack at it. Looking forward to running Nerves on the BBGG.

**Comment by fhunleth** [comment]
@jasonmj Could you try out the latest commit?

You'll need to either rebuild everything or run `make host-uboot-tools-rebuild all`.

**Comment by jasonmj** [comment]
@fhunleth This is great! Thank you! 

Personally, I’ve just left for vacation and won’t be able to test for a couple of weeks (sorry this timing isn’t great). 

However, my colleague, Charles, who also has a BBGG has been following along and may have a chance to test sooner. We’ll keep you posted.

**Comment by fhunleth** [comment]
Thanks to @jjcarstens, it works on BBB and PocketBeagle too.

For posterity, on the PocketBeagle, there are these logs but they exist in previous Nerves system releases:

```
iex(2)> RingLogger.grep "tps"

00:00:13.378 [warn]  tps65217-pmic: Failed to locate of_node [id: -1]

00:00:13.378 [warn]  tps65217-bl: Failed to locate of_node [id: -1]

00:00:13.378 [info]  tps65217 0-0024: TPS65217 ID 0xe version 1.2
```

**Comment by jasonmj** [comment]
I've tested the v2.13.3 release on my BBGG and found that WiFi works out of the box, but USB and Ethernet require some additional drivers. I've opened a new PR to add support for them to `nerves_system_bbb`: https://github.com/nerves-project/nerves_system_bbb/pull/251

Thanks again for pushing through the uboot upgrade to add device tree support!

**Comment by jasonmj** [comment]
I'm getting some unexpected results when adding a device tree overlays for a cape. The more overlays I add, the more I see `uboot_overlays: loading /lib/firmware/M-BB-BBGG-00A0.dtbo ...` printed on boot. Instead, I would expect to see the particular overlays I'm specifying in `fwup_include/provisioning.conf` like `uboot_setenv(uboot-env, "uboot_overlay_addr7", "/lib/firmware/BB-UART5-00A0.dtbo")`. Here's an example boot where I've added 8 overlays, just to emphasize the repetition: 

```
U-Boot 2021.10 (Feb 26 2021 - 22:02:47 +0000)

CPU  : AM335X-GP rev 2.1
Model: TI AM335x BeagleBone Black
DRAM:  512 MiB
Reset Source: Power-on reset has occurred.
RTC 32KCLK Source: External.
WDT:   Started with servicing (60s timeout)
MMC:   OMAP SD/MMC: 0, OMAP SD/MMC: 1
Loading Environment from MMC... OK
Board: BeagleBone Black
<ethaddr> not set. Validating first E-fuse MAC
BeagleBone Black:
Model: SeeedStudio BeagleBone Green Gateway:
BeagleBone Cape EEPROM: no EEPROM at address: 0x54
BeagleBone Cape EEPROM: no EEPROM at address: 0x55
BeagleBone Cape EEPROM: no EEPROM at address: 0x56
BeagleBone Cape EEPROM: no EEPROM at address: 0x57
Net:   Could not get PHY for ethernet@4a100000: addr 0
eth2: ethernet@4a100000
Saving Environment to MMC... Writing to MMC(0)... OK
board_name=[A335BNLT] ...
board_rev=[GG1A] ...
loading /zImage.a ...
2866176 bytes read in 186 ms (14.7 MiB/s)
uboot_overlays: [uboot_base_dtb=am335x-boneblack-uboot-univ.dtb] ...
uboot_overlays: Switching too: dtb=am335x-boneblack-uboot-univ.dtb ...
loading /boot/am335x-boneblack-uboot-univ.dtb ...
215402 bytes read in 33 ms (6.2 MiB/s)
uboot_overlays: [fdt_buffer=0x60000] ...
uboot_overlays: loading /lib/firmware/M-BB-BBGG-00A0.dtbo ...
1931 bytes read in 88 ms (20.5 KiB/s)
uboot_overlays: loading /lib/firmware/M-BB-BBGG-00A0.dtbo ...
1931 bytes read in 88 ms (20.5 KiB/s)
uboot_overlays: loading /lib/firmware/M-BB-BBGG-00A0.dtbo ...
1931 bytes read in 88 ms (20.5 KiB/s)
uboot_overlays: loading /lib/firmware/M-BB-BBGG-00A0.dtbo ...
1931 bytes read in 88 ms (20.5 KiB/s)
uboot_overlays: loading /lib/firmware/M-BB-BBGG-00A0.dtbo ...
1931 bytes read in 89 ms (20.5 KiB/s)
uboot_overlays: loading /lib/firmware/M-BB-BBGG-00A0.dtbo ...
1931 bytes read in 89 ms (20.5 KiB/s)
uboot_overlays: loading /lib/firmware/M-BB-BBGG-00A0.dtbo ...
1931 bytes read in 89 ms (20.5 KiB/s)
uboot_overlays: loading /lib/firmware/M-BB-BBGG-00A0.dtbo ...
1931 bytes read in 89 ms (20.5 KiB/s)
uboot_overlays: loading /lib/firmware/M-BB-BBGG-00A0.dtbo ...
1931 bytes read in 89 ms (20.5 KiB/s)
uboot_overlays: loading /lib/firmware/BB-BONE-eMMC1-01-00A0.dtbo ...
1614 bytes read in 50 ms (31.3 KiB/s)
uboot_overlays: loading /lib/firmware/BB-BBGG-WL1835-00A0.dtbo ...
3504 bytes read in 38 ms (89.8 KiB/s)
debug: [console=ttyS0,115200n8 coherent_pool=1M bone_capemgr.uboot_capemgr_enabled=1 root=/dev/mmcblk0p2 rootfstype=squashfs rootwait coherent_pool=1M net.ifnames=0 omap_wdt.early_enable=1 omap_wdt.timer_margin=120 quiet] ...
debug: [bootz 0x82000000 - 88000000] ...
Kernel image @ 0x82000000 [ 0x000000 - 0x2bbc00 ]
## Flattened Device Tree blob at 88000000
   Booting using the fdt blob at 0x88000000
   Loading Device Tree to 8ff67000, end 8fffffff ... OK

Starting kernel ...
```

I've tried to trace where this might be coming from and found [`0002-U-Boot-BeagleBone-Cape-Manager.patch`](https://github.com/nerves-project/nerves_system_bbb/blob/f59cdfe8dff877cd83ee18cbb6959acd2f209a96/uboot/0002-U-Boot-BeagleBone-Cape-Manager.patch). So far, I've been unsuccessful in trying to get other overlays to load. 

When I run `cmd("fw_printenv")` I do see that my overlays are specified as if they _should_ be loading: 

```
uboot_base_dtb=am335x-boneblack-uboot.dtb
uboot_base_dtb_univ=am335x-boneblack-uboot-univ.dtb
uboot_emmc=BB-BONE-eMMC1-01-00A0.dtbo
uboot_model=M-BB-BBGG-00A0.dtbo
uboot_overlay_addr0=/lib/firmware/BB-UART1-00A0.dtbo
uboot_overlay_addr1=/lib/firmware/BB-UART2-00A0.dtbo
uboot_overlay_addr2=/lib/firmware/BB-UART4-00A0.dtbo
uboot_overlay_addr3=/lib/firmware/BB-UART5-00A0.dtbo
```

It seems like maybe the logic in the patch file I mentioned above is loading the board's device tree, `/lib/firmware/M-BB-BBGG-00A0.dtbo`, repeatedly instead.

**Comment by fhunleth** [comment]
@jasonmj  Check out https://github.com/nerves-project/nerves_system_bbb/blob/main/uboot/uboot.env#L278 for the loading code.

However, I think Connor may have fixed this in https://github.com/nerves-project/nerves_system_bbb/pull/252/files.

**Comment by jasonmj** [comment]
Thanks @fhunleth, PR 252 fixed it. Seems like the Nerves ecosystem has really picked up the pace recently!

**Comment by fhunleth** [comment]
Great! 

Fwiw, I've felt like the Nerves ecosystem has really slowed down progress recently based on overall commits and new features. BBB, though, has had some good improvements recently thanks in part to you, this is good. I've learned that progress comes in fits and spurts, though, since a lot of features hang out in private repos for a while before people have time to commit upstream.

**Pull request merged**
