### PR TITLE
[WIP] updates to uboot environment to support running off of emmc

### LINKED ISSUE #94: Nerves won't boot off the Beaglebone Black emmc
### Environment

* Elixir version (`elixir -v`): 
```
Erlang/OTP 21 [erts-10.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]
Elixir 1.8.1 (compiled with Erlang/OTP 20)
```
* Nerves environment: (`mix nerves.env --info`)
```
|nerves_bootstrap| Environment Package List

  Pkg:         nerves_system_bbb
  Vsn:         2.1.2
  Type:        system
  BuildRunner: {Nerves.Artifact.BuildRunners.Local, []}

  Pkg:         nerves_system_br
  Vsn:         1.6.6
  Type:        system_platform
  BuildRunner: {nil, []}

  Pkg:         nerves_toolchain_arm_unknown_linux_gnueabihf
  Vsn:         1.1.0
  Type:        toolchain
  BuildRunner: {Nerves.Artifact.BuildRunners.Local, []}

  Pkg:         nerves_toolchain_ctng
  Vsn:         1.5.0
  Type:        toolchain_platform
  BuildRunner: {nil, []}

|nerves_bootstrap| Loadpaths Start


Nerves environment
  MIX_TARGET:   bbb
  MIX_ENV:      dev

|nerves_bootstrap| Environment Variable List
  target:     bbb
  toolchain:  /home/andrew/.nerves/artifacts/nerves_toolchain_arm_unknown_linux_gnueabihf-linux_x86_64-1.1.0
  system:     /home/andrew/.nerves/artifacts/nerves_system_bbb-portable-2.1.2
  app:        /home/andrew/test
|nerves_bootstrap| Loadpaths End
```

### Current behavior
I'm unable to get a project running on the beaglebone emmc. I've tried installing a nerves firmware image build from a new project onto the emmc from a debian sd card using fwup: `fwup -a -d /dev/mmcblk1 -i test.fw -t complete`, the write seems to succeed, but the I get the following output after removing the sdcard and rebooting:
```
U-Boot SPL 2018.07 (Jan 27 2019 - 16:27:38 +0000)
Trying to boot from MMC2
Loading Environment from MMC... Card did not respond to voltage select!
*** Warning - MMC init failed, using default environment
Failed (-5)
U-Boot 2018.07 (Jan 27 2019 - 16:27:38 +0000)
CPU  : AM335X-GP rev 2.1
I2C:   ready
DRAM:  512 MiB
No match for driver 'omap_hsmmc'
No match for driver 'omap_hsmmc'
Some drivers were not found
Reset Source: Global external warm reset has occurred.
Reset Source: Power-on reset has occurred.
RTC 32KCLK Source: External.
MMC:   OMAP SD/MMC: 0, OMAP SD/MMC: 1
Loading Environment from MMC... Card did not respond to voltage select!
*** Warning - MMC init failed, using default environment
Failed (-5)
Board: BeagleBone Black
<ethaddr> not set. Validating first E-fuse MAC
BeagleBone Black:
BeagleBone: cape eeprom: i2c_probe: 0x54:
BeagleBone: cape eeprom: i2c_probe: 0x55:
BeagleBone: cape eeprom: i2c_probe: 0x56:
BeagleBone: cape eeprom: i2c_probe: 0x57:
board_name=[A335BNLT] ...
board_rev=[00C0] ...
Card did not respond to voltage select!
Card did not respond to voltage select!
Card did not respond to voltage select!
gpio: pin 56 (gpio 56) value is 0
gpio: pin 55 (gpio 55) value is 0
gpio: pin 54 (gpio 54) value is 0
gpio: pin 53 (gpio 53) value is 1
Card did not respond to voltage select!
Card did not respond to voltage select!
switch to partitions #0, OK
mmc1(part 0) is current device
Scanning mmc 1:1...
gpio: pin 56 (gpio 56) value is 0
gpio: pin 55 (gpio 55) value is 0
gpio: pin 54 (gpio 54) value is 0
gpio: pin 53 (gpio 53) value is 1
switch to partitions #0, OK
mmc1(part 0) is current device
gpio: pin 54 (gpio 54) value is 1
Checking for: /uEnv.txt ...
Checking for: /boot.scr ...
Checking for: /boot/boot.scr ...
Checking for: /boot/uEnv.txt ...
super: SQUASHFS error: Can't find a SQUASHFS superblock on 00000000
** Unrecognized filesystem type **
super: SQUASHFS error: Can't find a SQUASHFS superblock on 00000000
** Unrecognized filesystem type **
** Invalid partition 5 **
** Invalid partition 6 **
** Invalid partition 7 **
=> 
```

### Expected behavior
The firmware image boots off the emmc.

### PR DESCRIPTION
**Pull request by aadavids**
Work in progress to resolve #94.
Replaced 0:x with ${mmcdev}:x in uboot.env as per @fhunleth's advice, but no luck getting it to work so far.

Current boot output:
```

U-Boot SPL 2018.07 (Feb 12 2019 - 17:19:27 -0500)
Trying to boot from MMC2
Loading Environment from MMC... Card did not respond to voltage select!
*** Warning - MMC init failed, using default environment

Failed (-5)


U-Boot 2018.07 (Feb 12 2019 - 17:19:27 -0500)

CPU  : AM335X-GP rev 2.1
I2C:   ready
DRAM:  512 MiB
No match for driver 'omap_hsmmc'
No match for driver 'omap_hsmmc'
Some drivers were not found
Reset Source: Power-on reset has occurred.
RTC 32KCLK Source: External.
MMC:   OMAP SD/MMC: 0, OMAP SD/MMC: 1
Loading Environment from MMC... Card did not respond to voltage select!
*** Warning - MMC init failed, using default environment

Failed (-5)
Board: BeagleBone Black
<ethaddr> not set. Validating first E-fuse MAC
BeagleBone Black:
BeagleBone: cape eeprom: i2c_probe: 0x54:
BeagleBone: cape eeprom: i2c_probe: 0x55:
BeagleBone: cape eeprom: i2c_probe: 0x56:
BeagleBone: cape eeprom: i2c_probe: 0x57:
board_name=[A335BNLT] ...
board_rev=[00C0] ...
Card did not respond to voltage select!
Card did not respond to voltage select!
Card did not respond to voltage select!
gpio: pin 56 (gpio 56) value is 0
gpio: pin 55 (gpio 55) value is 0
gpio: pin 54 (gpio 54) value is 0
gpio: pin 53 (gpio 53) value is 1
Card did not respond to voltage select!
Card did not respond to voltage select!
switch to partitions #0, OK
mmc1(part 0) is current device
Scanning mmc 1:1...
gpio: pin 56 (gpio 56) value is 0
gpio: pin 55 (gpio 55) value is 0
gpio: pin 54 (gpio 54) value is 0
gpio: pin 53 (gpio 53) value is 1
switch to partitions #0, OK
mmc1(part 0) is current device
gpio: pin 54 (gpio 54) value is 1
Checking for: /uEnv.txt ...
Checking for: /boot.scr ...
Checking for: /boot/boot.scr ...
Checking for: /boot/uEnv.txt ...
super: SQUASHFS error: Can't find a SQUASHFS superblock on 00000000
** Unrecognized filesystem type **
super: SQUASHFS error: Can't find a SQUASHFS superblock on 00000000
** Unrecognized filesystem type **
** Invalid partition 5 **
** Invalid partition 6 **
** Invalid partition 7 **
=> 
```

### CODE REVIEW

**Comment by fhunleth** [comment]
FYI - I'm working my way over to this. I need to get a `nerves_system_br` release finished before trying this. Probably won't get to it until this weekend.

**Comment by fhunleth** [comment]
I looked. This is not as straightforward and I remembered in the past.

Two things need to be updated: 1. which device has the U-Boot environment block and 2. which device has Linux and the device tree overlay files.

The change I though you could make by adding `${mmcdev}` half fixed the second part. It turns out that `$mmcdev` isn't defined any more and when it was a couple years, it looks like there was some logic to check setting it as `1` (eMMC) and then reverting to `0` (MicroSD). U-boot doesn't seem to know which device it was loaded from. (This is weird since U-boot gets loaded in two parts, so it seems like it has to know. I might try searching more even though I know from looking at the mmc code in U-Boot that this won't help with the other change.) Anyway, if you're always going to boot from eMMC, then I'd hardcode mmcdev to 1.

The other change is where to store the U-Boot environment. This is hardcoded in a C header file. I patched it in `uboot/0004-Add-MMC-environment-location.patch`, but I set it to `0`. 

The pain is that not all Beaglebone boards have eMMC so I can't hardcode this in `nerves_system_bbb`. 

I'll think about it more, but your best bet is to update that patch and hardcode mmcdev=1. Maybe this PR could be salvaged by hardcoding mmcdev=0 (at least the change is in one place instead of distributed through the file) and adding a short paragraph to the README.md about how to switch to eMMC.

**Comment by aadavids** [comment]
Thanks for your help here. I won't be able to get around to trying that
until Tuesday, but I'll let you know how it goes.

For my own use it's always going to boot off the emmc, so having to
hardcode it is fine. And I think what you've suggested would work for the
PR.

**Comment by aadavids** [comment]
Just as an update, I got it working, but I'm not sure if I fully understand why.

I had to make a couple extra changes, I've updated the PR so you can see.

Using the mmcdev variable didn't work, uboot generates this error: `** Bad device specification mmc ${mmcdev} **`. Seems like the variable isn't being evaluated properly, but I might be doing something wrong here. I'm using 1:x for the env in uboot for now.

I also had to change the uenv_root variables in uboot.env from mmcblk0pX to /dev/mmcblk1pX.

The other major change was to fwup.conf and erlinit.config, replacing references of mmcblk0 with mmcblk1. I had thought that in uboot mmc0 was the sd card, and mmc1 was the emmc, and in linux mmc0 is always the current mmc device. But without those changes, the writable application data partition was not initialized properly. Additionally, it appears that Nerves thinks the emmc is mmc1:
```
iex(6)> cmd "ls /dev/mmcblk*"
/dev/mmcblk1rpmb
/dev/mmcblk1p4
/dev/mmcblk1p3
/dev/mmcblk1p2
/dev/mmcblk1p1
/dev/mmcblk1boot1
/dev/mmcblk1boot0
/dev/mmcblk1
```

**Comment by aadavids** [comment]
Any advice for how to move forward? Do you think the best bet would be for me to summarize the changes required in the README? Maybe close this PR in this state to leave it as a reference for anyone in the future with the same problem?

**Comment by fhunleth** [comment]
Sorry, somehow I'm just seeing this now. I didn't mean to ignore you. This is helpful information. Let's leave the PR open for a bit longer. Thanks for digging into this.

**Comment by fhunleth** [comment]
Closing this since it is stale and there's no active work to do this. There are two workarounds that I know of:

1. Creating a custom system and making the `mmcblk0`/`mmcblk1` modifications throughout as mentioned in comments. There's a `rootdisk0` alias that we've been using on other systems like x86_64 that might be able to reduce some of the renames, but it can't fix everything.
2. Creating a custom board where the eMMC is connected to the same MMC bus as the MicroSD card on Beaglebones. This has one big drawback in that the AM335x limits you to <= 2GB eMMC parts on that bus for reasons that I don't understand. However, it's possible if you have a source for these (i.e., Kingston 4GB set to pSLC mode)

**Pull request closed without merging**
